"""empty message

Revision ID: 194f8aaed750
Revises: c918a510a0f9
Create Date: 2025-03-04 00:09:42.081546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '194f8aaed750'
down_revision = 'c918a510a0f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.alter_column('score',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.alter_column('score',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
